# Generated by Django 4.2.7 on 2023-11-04 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('text', 'Text Message')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_bathrooms', models.IntegerField()),
                ('has_basement', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='properties')),
                ('description', models.TextField(blank=True, null=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='homeowner.homeowner')),
            ],
        ),
    ]
